[package]
name = "mho"
version = "0.0.0"
publish = false
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.5"
env_logger = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
walkdir = "2"
clap = "3.0.0-beta.2"
